### ISSUE TITLE
Tables in markdown are not being rendered. 

### ISSUE THREAD

**Issue by mohamed-riza** [khalid-hussain/IIUM-Thesis-LaTeX-Class#1]
When trying to render a simple table like:
```
| sdasd     | adasdas | sadasds                      |
|-----------|---------|------------------------------|
| asdasdasd | dasd    | asd                          |
| d         | dasdas  | assdasdasdasdasdasdasdasdasd |
```
I hit into the error:

```
! LaTeX Error: Environment longtable undefined.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.21 \begin{longtable}
                      []{@{}lll@{}}
? 
```

I have tried rendering in normal markdown. It works fine. However, another issue is with column width. The Markdown seems to be giving equal spaces for each column. Therefore a column that contains only 1 character and a column that contains 50 characters have the same width, making the long columns illegible.

**Comment by khalid-hussain** [comment]
It should be fixed now.

To add captions, use the following format:

```
: The Table's Caption

| sdasd     | adasdas | sadasds                      |
|-----------|---------|------------------------------|
| asdasdasd | dasd    | asd                          |
| d         | dasdas  | assdasdasdasdasdasdasdasdasd |
```

It should give the following:

![table](https://cloud.githubusercontent.com/assets/3102714/21577220/46b35e84-cf8e-11e6-89e2-9e0c63067e5f.png)
