### ISSUE TITLE
All Dates should be in English

### ISSUE THREAD

**Issue by mohamed-riza** [khalid-hussain/IIUM-Thesis-LaTeX-Class#11]
All dates in the front matter should be in English

**Comment by khalid-hussain** [comment]
What are they in now? Transliterated Arabic?

**Comment by mohamed-riza** [comment]
In arabic. Front page its 1438 and the other page RAB¯I‘ AL-AWWAL 1438

**Comment by khalid-hussain** [comment]
These are defined by the user. It is not generated by the template.

Please see: https://github.com/khalid-hussain/IIUM-Thesis-LaTeX-Class/blob/master/iiumthesis-config.tex#L17-L19

The rest of the template uses these variables.

**Comment by mohamed-riza** [comment]
ok Thanks
