### ISSUE TITLE
Approvals pages for Master is not present

### ISSUE THREAD

**Issue by mohamed-riza** [khalid-hussain/IIUM-Thesis-LaTeX-Class#12]

**Comment by khalid-hussain** [comment]
I beg to differ: https://github.com/khalid-hussain/IIUM-Thesis-LaTeX-Class/blob/master/frontmatter/approvalPage-Masters.tex

**Comment by mohamed-riza** [comment]
hmm ok. How do I switch to the masters approvals page from the PhD one?

**Comment by khalid-hussain** [comment]
I don't understand you completely but you could just compile that one page.

**Comment by khalid-hussain** [comment]
Until I get time to figure out an elegant solution, just change the file here: https://github.com/khalid-hussain/IIUM-Thesis-LaTeX-Class/blob/master/thesis.tex#L208
