### ISSUE TITLE
Copyright page should have a box around it

### ISSUE THREAD

**Issue by mohamed-riza** [khalid-hussain/IIUM-Thesis-LaTeX-Class#13]

**Comment by khalid-hussain** [comment]
Do you mean the copyright pages?

**Comment by khalid-hussain** [comment]
All copyright pages have a trim frame around them. I just need to figure out how to the remove the middle of page marks.

![image](https://user-images.githubusercontent.com/3102714/47620427-ee698b00-db24-11e8-96c0-321aa2a97629.png)
