### ISSUE TITLE
Font size of front matter pages are smaller than the template. 

### ISSUE THREAD

**Issue by mohamed-riza** [khalid-hussain/IIUM-Thesis-LaTeX-Class#14]
Im not sure if this is all pages or only certain pages of the front matter.

**Comment by khalid-hussain** [comment]
Can you make sure?

**Comment by mohamed-riza** [comment]
Hmm I remember them comparing certain pages like the the following: 
![declaration](https://user-images.githubusercontent.com/3281968/36637324-e1675ae4-1a14-11e8-9c4d-b929ce444f67.png)
I dont know how to check the font size on the PDF.
