### ISSUE TITLE
How do we remove the proposal defense cover. 

### ISSUE THREAD

**Issue by mohamed-riza** [khalid-hussain/IIUM-Thesis-LaTeX-Class#15]
Both the page itself and from the TOC

**Comment by khalid-hussain** [comment]
Can you post a screenshot of the ToC, please?

**Comment by mohamed-riza** [comment]
![toc](https://user-images.githubusercontent.com/3281968/36632729-220a647e-19c5-11e8-9eef-01c685f91d6b.png)

Actually looking at the IIUM template. It seems that none of the front matter should be displayed on the TOC. The IIUM template looks fizzy in Libre office. Can you confirm this? If this is the case, how do we remove them all?

**Comment by khalid-hussain** [comment]
Please see [English Thesis Template-2016 v1.docx
](https://github.com/khalid-hussain/IIUM-Thesis-LaTeX-Class/raw/master/_reference/English%20Thesis%20Template-2016%20v1.docx)

This file is included in the `_reference` folder. I've downloaded both the references from the Centre for Postgraduate Studies (CPS) website: http://www.iium.edu.my/cps/resource-centre/media-downloads

If they have changed it in 2017, then I am unaware of that.

![image](https://user-images.githubusercontent.com/3102714/36632769-c04f63b4-19c5-11e8-8e4d-f95a60ff848d.png)

**Comment by khalid-hussain** [comment]
Also see Issue #17.
