### ISSUE TITLE
Unable to remove certain people from the approvals page

### ISSUE THREAD

**Issue by mohamed-riza** [khalid-hussain/IIUM-Thesis-LaTeX-Class#16]
For example, if you do not have a co-supervisor, the template doesn't give you an option to remove this. 

Additionally, if you do not know the examiner's names, the template doesn't allow you to keep their names blank(I dont want to keep it myInternalExaminer etc).

**Comment by khalid-hussain** [comment]
Is the co-supervisor the only person you need to be able to remove?

**Comment by khalid-hussain** [comment]
Co-supervisor is now optional: 3ed098cb96a8c8bbb3e4f832cd13f1a73e135d87

If you have a co-supervisor, uncomment the following: https://github.com/khalid-hussain/IIUM-Thesis-LaTeX-Class/blob/master/iiumthesis-config.tex#L49

Can you please elaborate the other problem with screenshots?
