### ISSUE TITLE
How to choose which contents show up on as front matter? 

### ISSUE THREAD

**Issue by mohamed-riza** [khalid-hussain/IIUM-Thesis-LaTeX-Class#17]
Eg: 
Master or PhD approvals page
The different copyrights page

**Comment by khalid-hussain** [comment]
All the front matter is included in [thesis.tex](https://github.com/khalid-hussain/IIUM-Thesis-LaTeX-Class/blob/master/thesis.tex#L171-L250). I've formatted it better in d9feb975272bbbf4b3c7162f08b2d97bc431077d

For example:
```tex
% Proposal Defense Cover
\includepdf[
  addtotoc={1,chapter,1,Proposal Defense Cover,Proposal Defense Cover}
]
{frontmatter/proposalDefenseCover.pdf}
```

To remove it from the ToC, comment out the line that starts with `addtotoc`:

```tex
% Proposal Defense Cover
\includepdf[
%  addtotoc={1,chapter,1,Proposal Defense Cover,Proposal Defense Cover}
]
{frontmatter/proposalDefenseCover.pdf}
```

To remove it from the ToC and the resultant file, comment out the whole command:

```tex
% Proposal Defense Cover
%\includepdf[
%  addtotoc={1,chapter,1,Proposal Defense Cover,Proposal Defense Cover}
%]
%{frontmatter/proposalDefenseCover.pdf}
```
