### ISSUE TITLE
Copyright page issues

### ISSUE THREAD

**Issue by mohamed-riza** [khalid-hussain/IIUM-Thesis-LaTeX-Class#19]
Apart from the box around the page, the copyright should also have the following modification: 

1. "Copyright c 2018 Name and International Islamic University Malaysia. All
rights reserved." should be 10pts
2. The student's copyright should not have IIUM for the above line, only the student's name. 
3. There should be a space after the thesis title

**Comment by khalid-hussain** [comment]
> 3. There should be a space after the thesis title

What do you mean? Is there no space now?

**Comment by mohamed-riza** [comment]
> What do you mean? Is there no space now?

Yup, there is no space after the thesis title on the copyright page.

**Comment by mohamed-riza** [comment]
oh, wait, not sure if this is after the latest commit.

**Comment by mohamed-riza** [comment]
Yes, now it is fine.
