### ISSUE TITLE
Give the make file the ability to generate all front matter pdf's in one go

### ISSUE THREAD

**Issue by mohamed-riza** [khalid-hussain/IIUM-Thesis-LaTeX-Class#3]
Currently, if the front matter is updated, we have to generate the pdf's one by one for each file. Therefore, if the make file could do this in one go, this would be awesome.

**Comment by khalid-hussain** [comment]
Check b9653d8ee91e96eb625e9b42b7bfe536549a7bfd to see if it fulfills your requirements.

This is a temporary solution as they only need to be generated once. Ideas are welcome.
I have to make use of a tool called `latexmk` if I want to insert this option into the makefile.
I don't know how to do that yet.

**Comment by mohamed-riza** [comment]
Oh yes, this is so much better. There is no need to add to the make file, the bash script is sufficient.
