### ISSUE TITLE
Support for psuedocode format

### ISSUE THREAD

**Issue by mohamed-riza** [khalid-hussain/IIUM-Thesis-LaTeX-Class#9]
Support for pseudocode format

**Comment by khalid-hussain** [comment]
Pandoc does not have specific markup for this requirement. However, LaTeX does. I've added the `algorithmicx` package to cater to your request.

Please see,
1. [TeX.SE: Write Pseudo code in LaTeX](http://tex.stackexchange.com/questions/163768/write-pseudo-code-in-latex)
2. [LaTeX Wikibook: Algorithms](https://en.wikibooks.org/wiki/LaTeX/Algorithms)
3. `algorithmicx` manual by running `texdoc algorithmicx` in the terminal.

**Comment by mohamed-riza** [comment]
Do we have to add any other packages for this?

**Comment by khalid-hussain** [comment]
I've added a sample pseduo code block in the content file and have added the respective packages to the main `tex` file. Please see commit af68ca8883616f60558890feec3e906e6d815d82
